name: Build

on:
  workflow_dispatch:

permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: "build.yml"
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  APP_NAME: mouse-clicker

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            platform: windows-x64
            ext: .exe
          - target: aarch64-pc-windows-msvc
            os: windows-latest
            platform: windows-arm64
            ext: .exe

          # macOS
          - target: x86_64-apple-darwin
            os: macos-latest
            platform: macos-x64
            ext: ""
          - target: aarch64-apple-darwin
            os: macos-latest
            platform: macos-arm64
            ext: ""

          # Linux
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
            platform: linux-x64
            ext: ""
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04-arm
            platform: linux-arm64
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Install Linux dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxdo-dev \
            libxcb1-dev \
            libxcb-render0-dev \
            libxcb-shape0-dev \
            libxcb-xfixes0-dev \
            libxkbcommon-dev \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Install Windows ARM64 tools
        if: matrix.os == 'windows-latest' && matrix.target == 'aarch64-pc-windows-msvc'
        run: |
          echo "Windows ARM64 target configured"

      - name: Set binary name
        run: |
          BINARY_NAME="${{ env.APP_NAME }}-${{ matrix.platform }}${{ matrix.ext }}"
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
        shell: bash

      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.target }} --verbose
        continue-on-error: false

      - name: Verify binary exists
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            ls -la target/${{ matrix.target }}/release/${{ env.APP_NAME }}.exe
          else
            ls -la target/${{ matrix.target }}/release/${{ env.APP_NAME }}
          fi
        shell: bash

      - name: Prepare binary (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          copy target\${{ matrix.target }}\release\${{ env.APP_NAME }}.exe ${{ env.BINARY_NAME }}

      - name: Prepare binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cp target/${{ matrix.target }}/release/${{ env.APP_NAME }} ${{ env.BINARY_NAME }}
          chmod +x ${{ env.BINARY_NAME }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}
          path: ${{ env.BINARY_NAME }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -la artifacts/

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find artifacts -type f -exec cp {} release-assets/ \;
          ls -la release-assets/

      - name: Delete existing release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete v0.0.0 --yes || true
          git push --delete origin v0.0.0 || true

      - name: Create new release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag v0.0.0
          git push origin v0.0.0
          gh release create v0.0.0 \
            --title "v0.0.0" \
            --notes "Automated release" \
            release-assets/*
